name: Deploy Portfolio
on:
  push:
    branches:
    - develop
env:
  AZURE_WEBAPP_NAME: PortOn20241204130107
  DOTNET_CORE_VERSION: 8.0.11
  SERVER_PROJECT_PATH: src/PortOn.Server/PortOn.Server.csproj
  CLIENT_PROJECT_PATH: src/PortOn.Wasm/PortOn.Wasm.csproj
  CONFIGURATION: Release

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    - name: Restore Server
      run: dotnet restore "${{ env.SERVER_PROJECT_PATH }}"
    
    - name: Build Server
      run: dotnet build "${{ env.SERVER_PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Publish Server
      run: dotnet publish "${{ env.SERVER_PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output server-publish
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: server-publish

  deploy-client:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    - name: Restore Client
      run: dotnet restore "${{ env.CLIENT_PROJECT_PATH }}"
    
    - name: Build Client
      run: dotnet build "${{ env.CLIENT_PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Publish Client
      run: dotnet publish "${{ env.CLIENT_PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output client-publish
    
    # GitHub Pages 배포를 위한 설정
    - name: Change base-tag in index.html
      run: |
        $indexPath = "client-publish/wwwroot/index.html"
        $content = Get-Content -Path $indexPath
        $content = $content -replace '<base href="/"', '<base href="/portfolio/"'
        $content | Set-Content -Path $indexPath
    
    # 404.html 페이지 생성 (GitHub Pages SPA 지원용)
    - name: Copy index.html to 404.html
      run: cp client-publish/wwwroot/index.html client-publish/wwwroot/404.html
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: client-publish/wwwroot
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
